# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Setup user-specific environment variables
EDITOR=vim
LESS=-Ri
LADSPA_PATH=/usr/lib64/ladspa

# User specific aliases and functions
alias toClip='xclip -i -selection clipboard'
alias localWebserver='http-server -c-1 -a 127.0.0.1'

# Set prompt to have inverted colors to make it stand out
PS1="\[\e[7m\][\u@\h \W]\$\[\e[0m\] "

# Load machine-specific configuration
if [ -f $HOME/.bashrc-specific ]; then
  source $HOME/.bashrc-specific
fi

# Load private configuration information
if [ -f $HOME/.bashrc-private ]; then
  source $HOME/.bashrc-private
fi
